version: "3.8"

services:
  velocity-service:
    build:
      context: velocity
    ports:
      - 25565:25577
    environment:
      - EULA=TRUE
      - CFG_FORWARDING_SECRET=this_is_a_secret

  survival-service:
    build:
      context: minecraft-server/1.17.1
      target: minecraft-1.17.1-fabric
    environment:
      - EULA=TRUE
      - CFG_FORWARDING_SECRET=this_is_a_secret
      - MODE=survival
      - WHITELIST=maboesanman
      - OPS=maboesanman

  survival-laurel-service:
    build:
      context: minecraft-server/1.18.1
      target: minecraft-1.18.1-fabric
    environment:
      - EULA=TRUE
      - CFG_FORWARDING_SECRET=this_is_a_secret
      - MODE=survival
      - WHITELIST=maboesanman
      - OPS=maboesanman

  creative-service:
    build:
      context: minecraft-server/1.17.1
      target: minecraft-1.17.1-carpet
    environment:
      - EULA=TRUE
      - CFG_FORWARDING_SECRET=this_is_a_secret
      - MODE=creative
      - WHITELIST=maboesanman
      - OPS=maboesanman
